package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

public class Frm_MovieLibrary extends javax.swing.JFrame {

    int xMouse, yMouse;

    public Frm_MovieLibrary() {
        initComponents();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("vista/Resources/icon.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MovieLlibrary = new javax.swing.JPanel();
        btn_exit = new javax.swing.JLabel();
        sidebar = new javax.swing.JLabel();
        lbl_btnDerecho = new javax.swing.JLabel();
        lbl_btnIzquierdo = new javax.swing.JLabel();
        lbl_userIcon = new javax.swing.JLabel();
        lbl_Poster = new javax.swing.JLabel();
        btn_singOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        MovieLlibrary.setBackground(new java.awt.Color(27, 27, 50));
        MovieLlibrary.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(245, 246, 247));
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setText("X");
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        MovieLlibrary.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
        });
        MovieLlibrary.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 50));

        lbl_btnDerecho.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        lbl_btnDerecho.setForeground(new java.awt.Color(245, 246, 247));
        lbl_btnDerecho.setText(">");
        lbl_btnDerecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MovieLlibrary.add(lbl_btnDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 30, 340));

        lbl_btnIzquierdo.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        lbl_btnIzquierdo.setForeground(new java.awt.Color(245, 246, 247));
        lbl_btnIzquierdo.setText("<");
        lbl_btnIzquierdo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MovieLlibrary.add(lbl_btnIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 330));

        lbl_userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Resources/icono-de-perfil.png"))); // NOI18N
        lbl_userIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MovieLlibrary.add(lbl_userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        lbl_Poster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MovieLlibrary.add(lbl_Poster, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 260, 340));

        btn_singOut.setBackground(new java.awt.Color(59, 59, 79));
        btn_singOut.setForeground(new java.awt.Color(245, 246, 247));
        btn_singOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Resources/cerrar-sesion.png"))); // NOI18N
        btn_singOut.setText("Sing Out");
        btn_singOut.setBorder(null);
        MovieLlibrary.add(btn_singOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MovieLlibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MovieLlibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }// GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_exitMouseEntered
        btn_exit.setForeground(new Color(255, 0, 0));
    }// GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_exitMouseExited
        btn_exit.setForeground(new Color(245, 246, 247));
    }// GEN-LAST:event_btn_exitMouseExited

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }// GEN-LAST:event_sidebarMouseDragged

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_sidebarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }// GEN-LAST:event_sidebarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MovieLibrary.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MovieLibrary.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MovieLibrary.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MovieLibrary.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MovieLibrary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MovieLlibrary;
    private javax.swing.JLabel btn_exit;
    public javax.swing.JButton btn_singOut;
    public javax.swing.JLabel lbl_Poster;
    public javax.swing.JLabel lbl_btnDerecho;
    public javax.swing.JLabel lbl_btnIzquierdo;
    public javax.swing.JLabel lbl_userIcon;
    private javax.swing.JLabel sidebar;
    // End of variables declaration//GEN-END:variables
}
