/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.table.DefaultTableModel;

public class Frm_library extends javax.swing.JFrame {

    int xMouse, yMouse;
    public DefaultTableModel modelo;

    public Frm_library() {
        initComponents();
        setIconImage(getIconImage());
        modelo = new DefaultTableModel();
        tbl_biblioteca.setModel(modelo);
    }

    @Override
    public Image getIconImage() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("vista/Resources/icon.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        lbl_goBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_biblioteca = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        txt_idbiliotecca = new javax.swing.JTextField();
        txt_idusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 27, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
        });
        jPanel1.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 340, 50));

        btn_exit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(245, 246, 247));
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setText("X");
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lbl_goBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_goBack.setForeground(new java.awt.Color(245, 246, 247));
        lbl_goBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Resources/flecha-izquierda (2).png"))); // NOI18N
        lbl_goBack.setText("Go Back");
        lbl_goBack.setToolTipText("");
        lbl_goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lbl_goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 0, 100, 50));

        tbl_biblioteca.setBackground(new java.awt.Color(27, 27, 50));
        tbl_biblioteca.setForeground(new java.awt.Color(245, 246, 247));
        tbl_biblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_biblioteca);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 200));

        btn_delete.setBackground(new java.awt.Color(59, 59, 79));
        btn_delete.setForeground(new java.awt.Color(245, 246, 247));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Resources/borrar.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 100, 40));

        txt_idbiliotecca.setBackground(new java.awt.Color(10, 10, 35));
        txt_idbiliotecca.setForeground(new java.awt.Color(245, 246, 247));
        txt_idbiliotecca.setBorder(null);
        jPanel1.add(txt_idbiliotecca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 20));

        txt_idusuario.setBackground(new java.awt.Color(10, 10, 35));
        txt_idusuario.setForeground(new java.awt.Color(245, 246, 247));
        txt_idusuario.setBorder(null);
        jPanel1.add(txt_idusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 100, 20));

        jLabel1.setForeground(new java.awt.Color(245, 246, 247));
        jLabel1.setText("idUsuario");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        jLabel2.setForeground(new java.awt.Color(245, 246, 247));
        jLabel2.setText("Idbiblioteca");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_sidebarMouseDragged

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        btn_exit.setForeground(new Color(255, 0, 0));
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        btn_exit.setForeground(new Color(245, 246, 247));
    }//GEN-LAST:event_btn_exitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_library.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_library().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_delete;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_goBack;
    private javax.swing.JLabel sidebar;
    public javax.swing.JTable tbl_biblioteca;
    public javax.swing.JTextField txt_idbiliotecca;
    public javax.swing.JTextField txt_idusuario;
    // End of variables declaration//GEN-END:variables
}
